# Generated by Django 2.1 on 2019-04-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_format',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
